name: Sphinx

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-documentation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install Datasketches and Sphinx
        run: python -m pip install . sphinx==7.2.4 sphinx-rtd-theme
      - name: Run Sphinx
        run: cd docs; make html
      - name: Pages Deployment
        uses: peaceiris/actions-gh-pages@v3.9.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build/html
          destination_dir: docs/${{ github.ref_name }}
          enable_jekyll: false
          allow_empty_commit: false
          force_orphan: false
          publish_branch: gh-pages
